//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_garagem : DbContext
    {
        public db_garagem()
            : base("name=db_garagem")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tb_acesso> tb_acesso { get; set; }
        public virtual DbSet<tb_adicional> tb_adicional { get; set; }
        public virtual DbSet<tb_cliente> tb_cliente { get; set; }
        public virtual DbSet<tb_garagem> tb_garagem { get; set; }
        public virtual DbSet<tb_marca> tb_marca { get; set; }
        public virtual DbSet<tb_modelo> tb_modelo { get; set; }
        public virtual DbSet<tb_veiculo> tb_veiculo { get; set; }
        public virtual DbSet<tb_venda> tb_venda { get; set; }
        public virtual DbSet<tb_vendedor> tb_vendedor { get; set; }
    }
}
