//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_acesso
    {
        public int id_acesso { get; set; }
        public string login_acesso { get; set; }
        public string senha_acesso { get; set; }
        public byte status_acesso { get; set; }
        public Nullable<int> garagem_id { get; set; }
        public Nullable<int> vendedor_id { get; set; }
        public short tipo_acesso { get; set; }
    
        public virtual tb_garagem tb_garagem { get; set; }
        public virtual tb_vendedor tb_vendedor { get; set; }
    }
}
