//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_modelo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_modelo()
        {
            this.tb_veiculo = new HashSet<tb_veiculo>();
        }
    
        public int id_modelo { get; set; }
        public string nome_modelo { get; set; }
        public int marca_id { get; set; }
        public int garagem_id { get; set; }
    
        public virtual tb_garagem tb_garagem { get; set; }
        public virtual tb_marca tb_marca { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_veiculo> tb_veiculo { get; set; }
    }
}
