//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_venda
    {
        public int id_venda { get; set; }
        public System.DateTime data_venda { get; set; }
        public decimal valor_venda { get; set; }
        public short tipo_pgto { get; set; }
        public string obs_venda { get; set; }
        public int veiculo_id { get; set; }
        public int vendedor_id { get; set; }
        public int cliente_id { get; set; }
        public int garagem_id { get; set; }
        public Nullable<decimal> comissao_venda { get; set; }
        public short situacao_venda { get; set; }
    
        public virtual tb_cliente tb_cliente { get; set; }
        public virtual tb_garagem tb_garagem { get; set; }
        public virtual tb_veiculo tb_veiculo { get; set; }
        public virtual tb_vendedor tb_vendedor { get; set; }
    }
}
