//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_veiculo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_veiculo()
        {
            this.tb_venda = new HashSet<tb_venda>();
            this.tb_adicional = new HashSet<tb_adicional>();
        }
    
        public int id_veiculo { get; set; }
        public string anofab_veiculo { get; set; }
        public string km_veiculo { get; set; }
        public decimal valorcompra_veiculo { get; set; }
        public decimal valorvenda_veiculo { get; set; }
        public short situacao_veiculo { get; set; }
        public string placa_veiculo { get; set; }
        public string obs_veiculo { get; set; }
        public int modelo_id { get; set; }
        public int garagem_id { get; set; }
        public System.DateTime data_entrada { get; set; }
    
        public virtual tb_garagem tb_garagem { get; set; }
        public virtual tb_modelo tb_modelo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_venda> tb_venda { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_adicional> tb_adicional { get; set; }
    }
}
