//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_vendedor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_vendedor()
        {
            this.tb_acesso = new HashSet<tb_acesso>();
            this.tb_cliente = new HashSet<tb_cliente>();
            this.tb_venda = new HashSet<tb_venda>();
        }
    
        public int id_vendedor { get; set; }
        public string nome_vendedor { get; set; }
        public string telefone_vendedor { get; set; }
        public string cpf_vendedor { get; set; }
        public string email_vendedor { get; set; }
        public string obs_vendedor { get; set; }
        public Nullable<decimal> comissao_vendedor { get; set; }
        public int garagem_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_acesso> tb_acesso { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_cliente> tb_cliente { get; set; }
        public virtual tb_garagem tb_garagem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_venda> tb_venda { get; set; }
    }
}
